[package]
name = "a3-audio"
description = "Audio engine: software mixer, cpal output, 3D spatialisation"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
a3-audio-formats.workspace = true
a3-config.workspace = true
cpal.workspace = true
glam.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
a3-gamedata.workspace = true

[lints]
workspace = true
