[package]
name = "a3-landscape"
description = "World config, surface types and terrain layer materials for a WRP terrain"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
a3-config.workspace = true
a3-core.workspace = true
a3-gamedata.workspace = true
a3-vfs.workspace = true
a3-wrp.workspace = true
glam.workspace = true
thiserror.workspace = true

[dev-dependencies]
a3-gamedata.workspace = true
a3-wrp.workspace = true
glam.workspace = true

[lints]
workspace = true
