[package]
name = "a3-tools"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[[bin]]
name = "a3-tools"
path = "src/main.rs"

[dependencies]
a3-core.workspace = true
a3-paa.workspace = true
a3-pbo.workspace = true
a3-vfs.workspace = true
a3-audio-formats.workspace = true
a3-config.workspace = true
a3-gamedata.workspace = true
a3-p3d.workspace = true
a3-wrp.workspace = true
png.workspace = true
tiff.workspace = true
anyhow.workspace = true
clap.workspace = true
glam.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
