[package]
name = "a3-sqf"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
description = "SQF language core: values, lexer, parser, compiler, command registry and VM"

[dependencies]
a3-preproc.workspace = true
thiserror.workspace = true
indexmap.workspace = true
fancy-regex.workspace = true

[dev-dependencies]
criterion.workspace = true
a3-vfs.workspace = true
a3-preproc.workspace = true

[[bench]]
name = "vm"
harness = false

[lints]
workspace = true
