"""Generate docs/re/data-inventory.md: every PBO/EBO in the game install with size and header data.

Usage:
    python tools/re/data_inventory.py [--root P:/a3-rust/oirignal] [--out docs/re/data-inventory.md]

The root defaults to the A3_ROOT environment variable. Only the PBO header (the property block and
the entry table) is read; file data is not touched.
"""

from __future__ import annotations

import argparse
import os
import struct
from collections import defaultdict
from pathlib import Path

VERS = 0x56657273  # "sreV" header-extension entry
CPRS = 0x43707273  # "Cprs" compressed entry


def read_cstr(f) -> bytes:
    out = bytearray()
    while True:
        c = f.read(1)
        if not c or c == b"\0":
            return bytes(out)
        out += c


def read_header(path: Path):
    """Return (properties, entry_count, compressed_entry_count, data_bytes)."""
    with open(path, "rb") as f:
        read_cstr(f)
        mime, _orig, _res, _ts, _size = struct.unpack("<5I", f.read(20))
        props = {}
        if mime == VERS:
            while True:
                k = read_cstr(f)
                if not k:
                    break
                props[k.decode("latin1")] = read_cstr(f).decode("latin1")
        else:
            f.seek(0)
        n = packed = data = 0
        while True:
            name = read_cstr(f)
            hdr = f.read(20)
            if len(hdr) < 20:
                break
            m, _o, _r, _t, size = struct.unpack("<5I", hdr)
            if not name:
                break
            n += 1
            data += size
            packed += m == CPRS
        return props, n, packed, data


def human(n: int) -> str:
    for unit in ("B", "KiB", "MiB", "GiB"):
        if n < 1024 or unit == "GiB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return str(n)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=os.environ.get("A3_ROOT"))
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[2] / "docs" / "re" / "data-inventory.md"))
    a = ap.parse_args()
    if not a.root:
        raise SystemExit("set A3_ROOT or pass --root")
    root = Path(a.root)

    files = sorted(p for p in root.rglob("*") if p.is_file() and p.suffix.lower() in (".pbo", ".ebo"))
    by_top = defaultdict(list)
    for p in files:
        rel = p.relative_to(root)
        by_top[rel.parts[0]].append(p)

    lines = [
        "# Game data inventory",
        "",
        "Generated by `python tools/re/data_inventory.py` from the install of build 2.22.0.154103",
        "(`A3_ROOT`). Sizes are file sizes. `entries` counts files in the PBO entry table; `prefix`",
        "and `version` come from the header property block. `.ebo` files are encrypted PBOs (see",
        "below). Inner-file statistics (types, counts per extension) are a separate task.",
        "",
        "## Totals",
        "",
        "| Top-level folder | .pbo | .ebo | Size |",
        "|---|---:|---:|---:|",
    ]
    total = 0
    for top, ps in sorted(by_top.items(), key=lambda x: x[0].lower()):
        size = sum(p.stat().st_size for p in ps)
        total += size
        npbo = sum(p.suffix.lower() == ".pbo" for p in ps)
        lines.append(f"| `{top}` | {npbo} | {len(ps) - npbo} | {human(size)} |")
    npbo = sum(p.suffix.lower() == ".pbo" for p in files)
    lines.append(f"| **total** | **{npbo}** | **{len(files) - npbo}** | **{human(total)}** |")
    lines += [
        "",
        "## Encrypted PBOs (`.ebo`)",
        "",
        "`.ebo` files keep a plain PBO header: the `sreV` property block (`prefix`, `version`, and",
        "for creator DLCs a `Mikero=DePbo.dll.*` packer tag) and the full entry table with names and",
        "sizes are readable. The file data is encrypted. The engine checks the extension (`.ebo`",
        "string at RVA 0x1a7867c in arma3_x64.exe). The decryption scheme is not reversed yet",
        "(follow-up issue).",
        "",
        "## Files per folder",
        "",
    ]
    for top, ps in sorted(by_top.items(), key=lambda x: x[0].lower()):
        lines += [f"### `{top}`", "", "| File | Size | Prefix | Entries | Cprs | Other properties |",
                  "|---|---:|---|---:|---:|---|"]
        for p in ps:
            try:
                props, n, packed, _ = read_header(p)
            except (OSError, struct.error) as e:
                props, n, packed = {"error": str(e)}, -1, -1
            other = "; ".join(f"{k}={v}" for k, v in props.items() if k != "prefix")
            rel = p.relative_to(root).as_posix()
            lines.append(f"| `{rel}` | {human(p.stat().st_size)} | `{props.get('prefix', '')}` | {n} | {packed} | {other} |")
        lines.append("")
    Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(files)} files, {human(total)} -> {a.out}")


if __name__ == "__main__":
    main()
