[package]
name = "a3-fsm"
description = "FSMs: the scripted (.fsm) and native (CfgFSMs) state machine definitions and the machine that runs them"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
a3-config.workspace = true
thiserror.workspace = true

[dev-dependencies]
a3-gamedata.workspace = true

[lints]
workspace = true
